/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // ─── Armarius Design Tokens ───
        vellum: '#F7F0E0',
        'vellum-deep': '#EDE4CE',
        'vellum-dark': '#E3D7BC',
        ink: '#2A2318',
        'ink-light': '#6B5E4E',
        'ink-muted': '#A89880',
        terracotta: '#C25E3A',
        'terracotta-light': '#D97B5A',
        'terracotta-dark': '#9E4A2C',
        gold: '#D4A843',
        'gold-light': '#E8C96A',
        'gold-muted': '#C4A55A',
        'status-online': '#4A9E6B',
        'status-working': '#D4A843',
        'status-idle': '#A89880',
        'status-offline': '#8B7A6A',
        'status-hung': '#C25E3A',
        'status-checking': '#D97B5A',
        'status-pending': '#D4A843',
        'status-invited': '#A89880',
        'status-revoked': '#8B7A6A',
        error: '#B84A32',
        'error-bg': '#F5DDD6',
        success: '#4A9E6B',
        'success-bg': '#D8EADD',
        warning: '#C4903A',
        'warning-bg': '#F5E8CC',
      },
      fontFamily: {
        display: ['Fraunces', 'Georgia', 'serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.02em' }],
        'display-lg': ['36px', { lineHeight: '1.15', fontWeight: '600', letterSpacing: '-0.01em' }],
        'display-md': ['28px', { lineHeight: '1.2', fontWeight: '600', letterSpacing: '-0.01em' }],
        'display-sm': ['22px', { lineHeight: '1.25', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '1.55', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '1.5', fontWeight: '400', letterSpacing: '0.01em' }],
        'body-xs': ['11px', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0.02em' }],
        'mono-md': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'mono-sm': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        'gilt': '0 8px 24px rgba(42,35,24,0.08)',
        'gilt-lg': '0 4px 16px rgba(42,35,24,0.06)',
      },
      zIndex: {
        'elevated': '10',
        'sticky': '50',
        'sidebar': '100',
        'overlay': '200',
        'modal': '300',
        'toast': '400',
        'tooltip': '500',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "pulse-dot": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(74, 158, 107, 0.4)" },
          "50%": { boxShadow: "0 0 0 4px rgba(74, 158, 107, 0)" },
        },
        "pulse-working": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(212, 168, 67, 0.4)" },
          "50%": { boxShadow: "0 0 0 4px rgba(212, 168, 67, 0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "pulse-dot": "pulse-dot 2s ease-in-out infinite",
        "pulse-working": "pulse-working 1s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
