"""sprint3 roles seat_grants project brief marius timers

Revision ID: 468899ef9a27
Revises: a40098b66ac7
Create Date: 2026-06-29 08:30:14.742572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468899ef9a27'
down_revision: Union[str, Sequence[str], None] = 'a40098b66ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('is_leader', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsibilities', sa.Text(), nullable=False),
    sa.Column('skill_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_project_id'), ['project_id'], unique=False)

    op.create_table('seat_grants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('role_key', sa.String(length=120), nullable=False),
    sa.Column('marius_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seat_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seat_grants_marius_id'), ['marius_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_grants_project_id'), ['project_id'], unique=False)

    # NOT NULL columns added to existing tables carry a one-time server_default so the
    # ALTER backfills any pre-existing rows (no prod data yet, but keeps it portable).
    with op.batch_alter_table('mariuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_status', sa.String(length=20), nullable=False, server_default='invited'))
        batch_op.add_column(sa.Column('enrollment_code', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('probe_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('backoff_step', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('next_probe_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('offline_since', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('turn_started_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='setup'))
        batch_op.add_column(sa.Column('objective', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('success_metrics', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('target_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('context', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('settings', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('created_by_user_id', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('settings')
        batch_op.drop_column('context')
        batch_op.drop_column('github_url')
        batch_op.drop_column('target_date')
        batch_op.drop_column('success_metrics')
        batch_op.drop_column('objective')
        batch_op.drop_column('status')

    with op.batch_alter_table('mariuses', schema=None) as batch_op:
        batch_op.drop_column('turn_started_at')
        batch_op.drop_column('offline_since')
        batch_op.drop_column('next_probe_at')
        batch_op.drop_column('backoff_step')
        batch_op.drop_column('probe_attempts')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('enrollment_code')
        batch_op.drop_column('invite_status')

    with op.batch_alter_table('seat_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seat_grants_project_id'))
        batch_op.drop_index(batch_op.f('ix_seat_grants_marius_id'))

    op.drop_table('seat_grants')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_project_id'))

    op.drop_table('roles')
    # ### end Alembic commands ###
