"""baseline schema

Revision ID: a40098b66ac7
Revises: 
Create Date: 2026-06-28 21:16:56.021045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40098b66ac7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_task_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('marius_id', sa.Uuid(), nullable=False),
    sa.Column('adapter_type', sa.String(length=80), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('session_params_json', sa.JSON(), nullable=False),
    sa.Column('session_display_id', sa.String(length=200), nullable=True),
    sa.Column('last_run_id', sa.Uuid(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marius_id', 'adapter_type', 'task_id', name='uq_session_marius_adapter_task')
    )
    with op.batch_alter_table('agent_task_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_task_sessions_marius_id'), ['marius_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_task_sessions_task_id'), ['task_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('marius_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('adapter_type', sa.String(length=80), nullable=False),
    sa.Column('wake_source', sa.String(length=40), nullable=False),
    sa.Column('trigger_detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('external_run_id', sa.String(length=200), nullable=True),
    sa.Column('session_id_before', sa.Text(), nullable=True),
    sa.Column('session_id_after', sa.Text(), nullable=True),
    sa.Column('usage_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('continuation_attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_output_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_marius_id'), ['marius_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_task_id'), ['task_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    op.create_table('wakeup_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('marius_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wakeup_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wakeup_requests_marius_id'), ['marius_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wakeup_requests_task_id'), ['task_id'], unique=False)

    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('owner_user_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('mariuses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('adapter_type', sa.String(length=80), nullable=False),
    sa.Column('adapter_config', sa.JSON(), nullable=False),
    sa.Column('skill_ids', sa.JSON(), nullable=False),
    sa.Column('owner_user_id', sa.String(length=200), nullable=True),
    sa.Column('agent_token', sa.String(length=120), nullable=True),
    sa.Column('liveness', sa.String(length=20), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mariuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mariuses_agent_token'), ['agent_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_mariuses_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('run_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_events_run_id'), ['run_id'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'slug', name='uq_skill_workspace_slug')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('assigned_marius_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=200), nullable=True),
    sa.Column('created_by_marius_id', sa.Uuid(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('in_progress_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assigned_marius_id'), ['assigned_marius_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('marius_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_task_id'), ['task_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('author_kind', sa.String(length=20), nullable=False),
    sa.Column('author_marius_id', sa.Uuid(), nullable=True),
    sa.Column('author_user_id', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('mentions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_task_id'))
        batch_op.drop_index(batch_op.f('ix_comments_created_at'))

    op.drop_table('comments')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_task_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_assigned_marius_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_workspace_id'))

    op.drop_table('skills')
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_events_run_id'))

    op.drop_table('run_events')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_workspace_id'))

    op.drop_table('projects')
    with op.batch_alter_table('mariuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mariuses_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_mariuses_agent_token'))

    op.drop_table('mariuses')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_owner_user_id'))

    op.drop_table('workspaces')
    with op.batch_alter_table('wakeup_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wakeup_requests_task_id'))
        batch_op.drop_index(batch_op.f('ix_wakeup_requests_marius_id'))

    op.drop_table('wakeup_requests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_task_id'))
        batch_op.drop_index(batch_op.f('ix_runs_status'))
        batch_op.drop_index(batch_op.f('ix_runs_marius_id'))
        batch_op.drop_index(batch_op.f('ix_runs_created_at'))

    op.drop_table('runs')
    with op.batch_alter_table('agent_task_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_task_sessions_task_id'))
        batch_op.drop_index(batch_op.f('ix_agent_task_sessions_marius_id'))

    op.drop_table('agent_task_sessions')
    # ### end Alembic commands ###
